cache:
  directories:
    - node_modules
# Set up environment variables for tests
env:
  global:
    # Use a better mocha reporter for Travis
    - MOCHA_REPORTER=spec
# Use the Travis Docker build system which is faster
sudo: false
# Specify to use node
language: node_js
  - "6"

before_script:
  - npm run setup

script:
  - npm run test

after_success:
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "minutes-timer-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "milan.rakos@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true