cache: npm

language: node_js
node_js:
  - node
scripts:
  - npm install codecov -g
after_success:
  - npm run report-coverage

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true